apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: pulsar-ingress-grafana
  namespace: pulsar
spec:
  listener:
    name: pulsar-grafana
    protocol: TCP
  upstreams:
  - name: pulsar-grafana
    service: pulsar-grafana
    port: 3000
  action:
    pass: pulsar-grafana
