apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: pulsar-ingress
  namespace: pulsar
spec:
  listener:
    name: pulsar
    protocol: TCP
  upstreams:
  - name: pulsar
    service: pulsar-proxy
    port: 6650
  action:
    pass: pulsar
