---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      nodeSelector:
        node-type: service
      containers:
      - name: openldap
        image: 10.160.16.60/tools/openldap:latest
        ports:
        - containerPort: 389
          name: openldap
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: false
        volumeMounts:
          - mountPath: /var/lib/ldap
            name: openldap-volume
      volumes:
        - name: openldap-volume
          hostPath:
            path: /opt/data/openldap
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
spec:
  selector:
   app: openldap
  ports:
  - name: openldap
    port: 389
    protocol: TCP

---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
 name: openldap
 namespace: openldap
spec:
 listener:
   name: openldap
   protocol: TCP
 upstreams:
 - name: openldap
   service: openldap
   port: 389
 action:
   pass: openldap