---
apiVersion: v1
kind: Namespace
metadata:
  name: resource-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-manager-api
  namespace: resource-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-manager-api
  template:
    metadata:
      labels:
        app: resource-manager-api
    spec:
      nodeSelector:
        node-type: service
      containers:
      - name: resource-manager-api
        image: 10.160.16.60/resource-manager/resource-manager-api
        imagePullPolicy: Always
        env:
        - name: DEBUG
          value: "False"
        - name: LISTEN_PORT
          value: "8001"
        ports:
        - containerPort: 8001
          name: res-mgr-api
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: false
        # resources:
        #   requests:
        #     cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-manager-worker
  namespace: resource-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-manager-worker
  template:
    metadata:
      labels:
        app: resource-manager-worker
    spec:
      nodeSelector:
        node-type: service
      containers:
      - name: resource-manager-worker
        image: 10.160.16.60/resource-manager/resource-manager-worker
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
        # resources:
        #   requests:
        #     cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: resource-manager-api
  namespace: resource-manager
spec:
  selector:
   app: resource-manager-api
  ports:
  - name: res-mgr-api
    port: 8001
    protocol: TCP

---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
 name: test-assistant
 namespace: model-services
spec:
 listener:
   name: resource-manager
   protocol: TCP
 upstreams:
 - name: resource-manager
   service: resource-manager-api
   port: 8001
 action:
   pass: resource-manager

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: resource-manager-route
  namespace: resource-manager
spec:
  host: 10.160.13.15
  upstreams:
  - name: resource-manager-svc
    service: resource-manager-api
    port: 8001
  subroutes:
  - path: /resourcesmanager
    action:
      pass: resource-manager-svc

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: image-classifier-hpa
#   namespace: model-services
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: image-classifier
#   minReplicas: 1
#   maxReplicas: 4
#   targetCPUUtilizationPercentage: 90

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: resource-manager
  labels:
    name: redis-master
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      nodeSelector:
        node-type: service
      containers:
      - name: redis-master
        image: redis:6.0.9-alpine
        command:
          - "redis-server"
        args:
          - "/data/redis.conf"
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-data-res-manager
            mountPath: /data
      volumes:
        - name: redis-data-res-manager
          hostPath:
            path: /opt/data/resource_manager/redis-master
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: resource-manager
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  selector:
    name: redis-master
