# k8s deployment use
#db: mongodb://fos:fos@mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017/fos?replicaSet=mongodb&tls=true&tlsInsecure=true

# None k8s, external access. need update hosts file or in dns
db: mongodb://fos:fos@mongodb-0.qtf.fortinetqa.com:30001,mongodb-1.qtf.fortinetqa.com:30002,mongodb-2.qtf.fortinetqa.com:30003/fos?replicaSet=mongodb&tls=true&tlsInsecure=true
default_db: fos

redis:
  server: 10.160.27.113
  port: 6379

infosite:
  ftp_ip: 172.16.100.71
  ftp_user: abc
  ftp_password: xxxxx
  check_interval: 3600

targets:
  - product: FortiOS
    version: v7.00

job:
  timeout: 3600