service_config:
    services:
#        - platform_operator
#        - resource_manager
#        - image_classifier
#        - scale_controller
#        - benchmark
#        - monitor
#        - qr_display
#        - fos
#        - -k8s
#        - bpproxy
#        - bpmanager
        - upgrade