---
jenkins_info:
  ip: "http://10.160.13.30:8080"
  username: "taas-api"
  password: "118eed0315e68f05695c4db245f358f2d0"
  jobs:
    iPhone12-ios17: "mobile_test/FortiToken_Mobile/iOS/iPhone12-ios17/ios17_auto_test"
    iPhone8-ios16: "mobile_test/FortiToken_Mobile/iOS/iPhone8-ios16/ios16_auto_test"
    iPhone11-ios18: "mobile_test/FortiToken_Mobile/iOS/iPhone11-ios18/ios18_auto_test"
    iPhone7-ios15: "mobile_test/FortiToken_Mobile/iOS/iPhone7-ios15/ios15_auto_test"

jobs_type:
  mobile:
    - "mobile_test/FortiToken_Mobile/iOS"
    - "mobile_test/FortiToken_Mobile/android"
  gui:
    - "xx"
    - "yy"
  api:
    - "xx"
    - "yy"
rabbitmq: amqp://taas:taas@10.160.13.60:5672/taas
push_gateway: 10.160.13.11:9091
mongodb:
  server: 10.160.13.60:27017
  collection: jenkins_cloud
