---
data_save_path: /data
pulling_interval: 10
pushgateway_ip: 10.160.83.213:9091
snmp_exporter_ip: 10.160.83.213:9116
wait_seconds_after_notify: 120
notifier_check_interval_seconds: 10
pulsar_ip: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
pulsar_topic: non-persistent://public/default/scale_controller
redis_server: 10.160.13.13
redis_port: 6379
elastic_search_engine: 10.160.77.150:8086
elastic_search_credential: "customer:elastic"
config_download_server: 10.160.50.118:8889
grafana_dash_board:
  ftc: http://10.160.83.213:3000/d/O9k5qKpGz/ftc-scaling-perf-test?orgId=1
  fil: http://10.160.83.213:3000/d/1V34bd5Gk/fortiisolator-scaling-test?orgId=1
db:
  cluster_ips: [10.160.83.213]
  username: "taas"
  password: "taas"
  dc: dc1
