cassandra:
  version: "3.11.10"
  cassandraLibDirVolume:
    storageClass: local-path
    size: 100Gi
  allowMultipleNodesPerWorker: true
  heap:
   size: 1G
   newGenSize: 1G
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  datacenters:
  - name: dc1
    size: 1
    racks:
    - name: r1
      affinityLabels:
        kubernetes.io/hostname: kubecluster-1-node1
#kube-prometheus-stack:
#  grafana:
#    adminUser: admin
#    adminPassword: admin123
#stargate:
#  enabled: true
#  replicas: 1
#  heapMB: 256
#  cpuReqMillicores: 200
#  cpuLimMillicores: 1000
