apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cluster-ingress-13.15
  namespace: default
spec:
  host: 10.160.13.15
  routes:
  - path: /scale
    route: scale-controller/scale-controller-route
  - path: /imageclassifier
    route: model-services/image-classifier-route
  - path: /resourcesmanager
    route: resource-manager/resource-manager-route
  - path: /monitor
    route: monitor-service/monitor-service-route
  - path: /benchmark
    route: benchmark/benchmark-api-route
