apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cluster-ingress
  namespace: default
spec:
  host: 10.160.13.11
  routes:
  - path: /scalecontroller
    route: scale-controller/scale-controller-route
  - path: /imageclassifier
    route: model-services/image-classifier-route
  - path: /resourcesmanager
    route: resource-manager/resource-manager-route
  - path: /monitor
    route: monitor-service/monitor-service-route
