apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: test-assistant
  namespace: model-services
spec:
  listener:
    name: test-assistant
    protocol: TCP
  upstreams:
  - name: test-assistant
    service: model-service
    port: 8000
  action:
    pass: test-assistant
