---
rabbitmq: amqp://taas:taas@10.43.88.181:5672/taas
push_gateway: 10.160.13.11:9091
redis:
  server: 10.160.13.11
  port: 6379
db:
  cluster_ips:
    - 10.160.13.60
  username: taas
  password: taas
  dc: dc1
