---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: model-services-ingress
  namespace: model-services
spec:
  host: 10.160.13.11
  upstreams:
  - name: imageclassifier
    service: model-service
    port: 8000
  routes:
  - path: /imageclassifier
    action:
      pass: imageclassifier

