---
pulling_interval: 5
pushgateway_ip: localhost
redis_server: localhost
redis_port: 6379
db: mysql+pymysql://root:fortinet@10.160.13.11/monitor
service_ip: 10.160.13.10

alert_system:
  opsgenie:
    api_key: xxxxxx

metrics:
  FTC_LOGIN:
    alert_freq: once
    alert_type: opsgenie
    description: FTC login alert
    thres_hold: 1
    disable_alert: True
    compare: ge # ge=Greater and equal(than), le=less and equal(than),thres_hold
    alert_payload:
      message: FTC login fail!
      source: ftc-login-checker
      description: FTC login failure!
      responders:
        - name: sunnyvale-maas-infra
          type: team
      visible_to:
        - name: sunnyvale-maas-infra
          type: team
      details:
        Product: FAS
        Type: Test
      priority: P1
