---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackboxexporter-config
  namespace: monitor-system
data:
  blackbox.yml: |
    modules:
      ftc_portal_check:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: []  # Defaults to 2xx
          method: GET
          headers:
            Host: ftc.fortinet.com/version
            Accept-Language: en-US
            Origin: infra-service
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          fail_if_body_not_matches_regexp:
            - "\"ftc_portal\":*"
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4" # defaults to "ip6"
          ip_protocol_fallback: false  # no fallback to "ip6"

      dns_udp_resolve:
        prober: dns
        timeout: 5s
        dns:
          query_name: "ftc.fortinet.com"
          query_type: "A"
          valid_rcodes:
          - NOERROR
          validate_answer_rrs:
            fail_if_matches_regexp:
            - ".*127.0.0.1"
            fail_if_all_match_regexp:
            - ".*127.0.0.1"
            #fail_if_not_matches_regexp:
            #- "ftc.*"
            #fail_if_none_matches_regexp:
            #- "ftc.*"
          validate_authority_rrs:
            fail_if_matches_regexp:
            - ".*127.0.0.1"
          validate_additional_rrs:
            fail_if_matches_regexp:
            - ".*127.0.0.1"

      ping:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: "ip4"

