---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-41-24
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-41-24
  template:
    metadata:
      labels:
        app: esxi-expr-41-24
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.41.24'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-41-24
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-41-24
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-70
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-70
  template:
    metadata:
      labels:
        app: esxi-expr-1-70
    spec:
      containers:
      - name: esxi-exporter-1-70
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.70'
          - '-username=root'
          - '-password=Fortinet_123'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service

---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-70
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-70
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-69
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-69
  template:
    metadata:
      labels:
        app: esxi-expr-1-69
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.69'
          - '-username=root'
          - '-password=Fortinet_123'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-69
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-69
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-52
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-52
  template:
    metadata:
      labels:
        app: esxi-expr-1-52
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.52'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-52
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-52
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-53
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-53
  template:
    metadata:
      labels:
        app: esxi-expr-1-53
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.53'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-53
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-53
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-55
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-55
  template:
    metadata:
      labels:
        app: esxi-expr-1-55
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.55'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-55
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-55
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-59
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-59
  template:
    metadata:
      labels:
        app: esxi-expr-1-59
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.59'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-59
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-59
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-68
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-68
  template:
    metadata:
      labels:
        app: esxi-expr-1-68
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.68'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-68
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-68
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-67
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-67
  template:
    metadata:
      labels:
        app: esxi-expr-1-67
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.67'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-67
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-67
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-1-66
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-1-66
  template:
    metadata:
      labels:
        app: esxi-expr-1-66
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.1.66'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-1-66
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-1-66
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-13-3
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-13-3
  template:
    metadata:
      labels:
        app: esxi-expr-13-3
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.65.13.3'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-13-3
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-13-3
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-13-5
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-13-5
  template:
    metadata:
      labels:
        app: esxi-expr-13-5
    spec:
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.65.13.5'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
      nodeSelector:
        node-type: service
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-13-5
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-13-5
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP