---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-41-24
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-41-24
  template:
    metadata:
      labels:
        app: esxi-expr-41-24
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kubecluster-1-node1
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.41.24'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-41-24
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-41-24
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esxi-expr-50-117
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esxi-expr-50-117
  template:
    metadata:
      labels:
        app: esxi-expr-50-117
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kubecluster-1-node1
      containers:
      - name: esxi-exporter
        image: 10.160.16.60/tools/prometheus-vmware-exporter
        args:
          - '-host=10.160.50.117'
          - '-username=root'
          - '-password=fortinet'
        ports:
        - containerPort: 9512
          name: esxi-exporter
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: esxi-expr-50-117
  namespace: monitor-system
spec:
  selector:
   app: esxi-expr-50-117
  ports:
  - name: esxi-exporter
    port: 9512
    protocol: TCP