---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstack-exporter
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstack-exporter
  template:
    metadata:
      labels:
        app: openstack-exporter
    spec:
      nodeSelector:
        node-type: service
      containers:
      - name: openstack-exporter
        image: quay.io/niedbalski/openstack-exporter-linux-amd64:v1.4.0
        ports:
        - containerPort: 9116
          name: snmp-exporter
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/snmp_exporter
            name: snmpexporter-config
      volumes:
        - name: snmpexporter-config
          configMap:
            name: snmpexporter-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: monitor-system
spec:
  selector:
   app: snmp-exporter
  ports:
  - name: snmp-exporter
    port: 9116
    protocol: TCP
---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
 name: snmp-exporter-ts
 namespace: monitor-system
spec:
 listener:
   name: snmpexporter
   protocol: TCP
 upstreams:
 - name: snmpexporter
   service: snmp-exporter
   port: 9116
 action:
   pass: snmpexporter

