---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kubecluster-1-node1
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter
        ports:
        - containerPort: 9116
          name: snmp-exporter
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/snmp_exporter
            name: snmpexporter-config
      volumes:
        - name: snmpexporter-config
          configMap:
            name: snmpexporter-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: monitor-system
spec:
  selector:
   app: snmp-exporter
  ports:
  - name: snmp-exporter
    port: 9116
    protocol: TCP
---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
 name: snmp-exporter-ts
 namespace: monitor-system
spec:
 listener:
   name: snmpexporter
   protocol: TCP
 upstreams:
 - name: snmpexporter
   service: snmp-exporter
   port: 9116
 action:
   pass: snmpexporter

