version: '2.0'
services:
  jupyter_lab:
    image: 10.160.16.60/jupyterlab/jupyterlab_no_kernel
    ports:
        - "8888:8888"
    restart: always
    volumes:
        - /home/jenkins:/shared_folder

  httpd:
    image: httpd:2.4
    ports:
        - "8889:80"
    restart: always
    volumes:
        - /home/jenkins/custom_config/models/:/usr/local/apache2/htdocs/


